default_language_version:
  python: python3.8

repos:
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.2
  hooks:
  - id: flake8
- repo: https://github.com/timothycrosley/isort
  rev: 4.3.21
  hooks:
    - id: isort
      additional_dependencies:
        - isort[pyproject]
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
